name: C++ CI

on:
  push:
    branches:
      - master
      - '*/*'

jobs:
  build_x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_READ }}

      - name: Set up Docker container
        run: |
          docker pull ghcr.io/piotrciosmak/height-vision-pi/x64:0.3.1

      - name: Build and run tests inside Docker
        run: |
          docker run --network host -v /run/udev:/run/udev -v $(pwd):/Height_Vision_Pi --entrypoint /bin/bash ghcr.io/piotrciosmak/height-vision-pi/x64:0.3.1 -c "
            cmake -S /Height_Vision_Pi -B /Height_Vision_Pi/build -DENABLE_TESTS=ON
            cmake --build /Height_Vision_Pi/build --target AllUnitTests -- -j$(nproc) &&
            cd ./build/tests/unit &&
            ./AllUnitTests
          "